### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by aotumanbiu** [1010code/OneClass_NeuralNetwork#1]
我根据你的代码和官方提供的代码，做了一个pytorch版本的 ，但是最后的得到的结果却不能像您代码中的那么好，所以麻烦问一下，您有pytorch版本的代码吗

**Comment by andy6804tw** [comment]
@aotumanbiu Hi, 我這裡目前只有 TensorFlow 版本的程式碼。

**Comment by aotumanbiu** [comment]
@andy6804tw 感谢您的回复，经过一些思考，我在训练的时候加入了一些负样，优化了训练的细节，在训练了4epoch后，对于测试集就达到了 91.8% 的准确率，再次感谢您的回复。

**Comment by 1170953489** [comment]
> @andy6804tw 感谢您的回复，经过一些思考，我在训练的时候加入了一些负样，优化了训练的细节，在训练了4epoch后，对于测试集就达到了 91.8% 的准确率，再次感谢您的回复。

但是加了负样本的话就不是单纯的一分类了呀
